### ISSUE TITLE
[Question] - plugins

### ISSUE THREAD

**Issue by dazinator** [yuriy-nelipovich/DependencyInjection.Extensions#1]
I am developing a modular system, would the following usage work?

```
// When system starts up:
    services.AddTransient<DefaultService>();
  
    services.AddByName<IService>()
        .Add<DefaultHostService>("default");


// When module A starts up (registering against same IServiceCollection):

   services.AddByName<IService>()
        .Add<FooService>("foo");


// When module B starts up (registering against same IServiceCollection):

   services.AddByName<IService>()
        .Add<BarService>("bar");

     

// Back in host:

        services .Build();

```

I am wondering if multiple calls to `services.AddByName<IService>()` in order to add each named registration would cause any problems?

**Comment by nullptre** [comment]
This call will not compile:

`services .Build();`

because the `Build()` method is not extension method and is located in `ServicesByNameBuilder` class.

To achieve your goal you have to call `services.AddByName<IService>()` only once per `IServiceCollection` and then pass this single `ServicesByNameBuilder` instance to all modules. And after that you can call 

        // Back in host:

        servicesByNameBuilder.Build();

So this means that `services.AddByName<IService>()` method returns new instance of `ServicesByNameBuilder`. However the final registration in the service collection occurs when you call `ServicesByNameBuilder.Build()` method. So that means it will register only services that are added to this particular `ServicesByNameBuilder`.

**Comment by dazinator** [comment]
Ok thanks, thats what I was afraid of.. :-)

**Comment by nullptre** [comment]
Please let me know if my solution worked for you ;) Thanks

**Comment by dazinator** [comment]
@yuriy-nelipovich - It helped clarify the situation, thanks. I was just thinking about how I might work this into my module bootstrapping API's. I know I should be able to achieve this now.
