### ISSUE TITLE
[Idea] Change IServiceByName<T> to something lib agnostic

### ISSUE THREAD

**Issue by dadhi** [yuriy-nelipovich/DependencyInjection.Extensions#13]
Hi, nice library here :)

I have an improvement idea regarding usage of `IServiceByName<T>` at injection side. 

It requires reference to your library. If the project where injection happens is not a composition root, e.g. some business logic, that's may be too much of implementation detail leaking. Basically, there is the type of specific DI library in my logic.

Could it be replaced or **at least exist an alternative with BCL** type? 

For instance, `Func<string, T>`, `IDictionary<string, T>`, or `ValueTuple(string, T)`.

Note, It may lose the factory semantic of  `IServiceByName<T>` but we don't have this semantic for injection without key anyway.

**Comment by nullptre** [comment]
Injecting a **BCL** type is not a good idea because it may conflict with other registrations of the same type. If you want to get rid of dependency on `IServiceByName<T>` I recommend to use factory registration approach as described in readme.

If you still need a dynamic resolution of keys during runtime, then your business level project may declare its own `IMyServiceByNameFactory` interface and then you map it to a custom implementation (i.e. adapter) `MyServiceByNameAdapter` which actually uses the library and adapts `IServiceByName<T>` to `IMyServiceByNameFactory`.
